name: vpn_detector
description: Detect VPN connections on [Android and IOS]
version: 1.0.1
repository: https://github.com/aelahmar/vpn_detector

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=3.3.9"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.aelahmar.vpn_detector
        pluginClass: VpnDetectorPlugin
      ios:
        pluginClass: VpnDetectorPlugin
