name: vpn_detector
description: A Flutter package for reliable VPN detection on iOS and Android, featuring a clean, testable API and real-time status updates.
version: 1.2.0
repository: https://github.com/aelahmar/vpn_detector

environment:
  sdk: ">=2.18.5 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  connectivity_plus: ^6.1.4
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  coverage: ^1.15.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aelahmar.vpn_detector
        pluginClass: VpnDetectorPlugin
      ios:
        pluginClass: VpnDetectorPlugin